const ROOT_POSTS = document.getElementById('posts')
const ROOT_HEADER = document.getElementById('header')
const ROOT_ARCHIVE = document.getElementById('archive')
const ROOT_SPINNER = document.getElementById('spinner')
const ROOT_ERROR = document.getElementById('error')
